# Generated by Django 4.0 on 2021-12-22 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_aboutus_chef'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aboutus',
            new_name='About',
        ),
    ]
